#!/bin/bash

<?JS if (type=="devel") { ?>

workspace="<?JS root ?>";
projects=`cd $workspace/; ls -d */`;

out=$(mktemp)

for project in $projects; do
	cpPath="$workspace/${project}.classpath"

eworkspace=`echo $workspace | sed -e 's/\//\\\\\//'`
eproject=`echo $project | sed -e 's/\//\\\\\//'`

	grep 'kind="lib"' $cpPath | egrep -o 'path=\".*?\"' | cut -f2 -d'"' | sed -e "s/^\([^/]\)/$eworkspace\\/${project}\1/" >> $out
	grep 'kind="output"' $cpPath | egrep -o 'path=\".*?\"' | cut -f2 -d'"' | sed -e "s/^\([^/]\)/$eworkspace\\/${eproject}\1/" >> $out

done


cp=`sort -u $out | xargs | tr " " ":"`
rm $out

echo -n "$cp:$HOME/.gedi/plugins/.*"

<?JS } else  { ?>

echo -n "<?JS root ?>/gedi.jar:<?JS root ?>/lib/.*:$HOME/.gedi/plugins/*"

<?JS }  ?>
